### ISSUE TITLE
TIP: Cache the TypeFace

### ISSUE THREAD

**Issue by mindshifter** [payworks/mpos-ui.android.paybutton#1]
You should cache the TypeFace, otherwise you might risk memory leaks on older handsets. Caching will increase speed as well since it's not super fast to read from assets all the time.

https://github.com/payworks/mpos-ui.android.paybutton/blob/master/mpos-ui/src/main/java/io/mpos/ui/shared/util/UiHelper.java#L75

**Comment by redshift13** [comment]
Thank you for the suggestion, this will make it into the next release.
